require:
 - rubocop-performance
 - rubocop-rake
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false
