require:
 - rubocop-performance
 - rubocop-rake
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
  NewCops: enable

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'

Metrics/ClassLength:
  Max: 110

Metrics/ModuleLength:
  Max: 130

Metrics/MethodLength:
  Max: 20

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ClassVars:
  Exclude:
  - 'tasks/helpers/folio_request.rb'

Style/SlicingWithRange:
  Enabled: false
