okapi:
  url: http://example.com
  headers:
    X-Okapi-Tenant: sul
    User-Agent: FolioApiClient
  login_params:
    username: user
    password: pass

tsv: spec/fixtures/tsv

hostname: https://folio-test.stanford.edu
namespace: folio-test
configurations:
  - CHECKOUT

# we test against real data we GET from FOLIO before migrating
json: spec/fixtures/json
