name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install --without production
    - name: Run Rubocop
      run: bundle exec rake rubocop
    - name: Run tests
      run: bundle exec rspec
