name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install --without production
    - name: Run Rubocop
      run: bundle exec rake rubocop
    - name: Prepare test directories
      run: |
        mkdir -p spec/fixtures/acquisitions/orders/json/law
        mkdir -p spec/fixtures/acquisitions/orders/json/sul
    - name: Run tests
      run: bundle exec rspec
