name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:

    - name: Extract branch name
      id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/sul-dlss/folio-tasks
        file: Dockerfile

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
    - name: Install dependencies
      run: bundle install --without production
    - name: Run Rubocop
      run: bundle exec rake rubocop
    - name: Prepare test directories
      run: |
        mkdir -p spec/fixtures/acquisitions/orders/json/law
        mkdir -p spec/fixtures/acquisitions/orders/json/sul
    - name: Run tests
      run: bundle exec rspec
